name: Documentation
on:
  push:
    branches: [master]
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          # Build documentation on the latest Julia 1.x
          version: '1'
      - name: Install dependencies
        shell: julia --project=docs {0}
        run: |
          using Pkg
          Pkg.add([
              PackageSpec(name="SemialgebraicSets", rev="master"),
              PackageSpec(name="MultivariateMoments", rev="master"),
              PackageSpec(name="MultivariateBases", rev="master"),
              PackageSpec(name="MultivariatePolynomials", rev="master"),
              PackageSpec(name="SumOfSquares", rev="master"),
              PackageSpec(name="PolyJuMP", rev="master"),
          ])
          Pkg.instantiate()
          Pkg.develop(PackageSpec(path=pwd()))
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ --code-coverage=user docs/make.jl
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
